
const $=id=>document.getElementById(id);let matrixSelect=0xff,columns=new Uint8Array(6);columns.fill(0xff),slider=0;let nvram=new Uint8Array(0x8000),ledByte=0xff,dmBytes=[],lastCmd=null,cmdCount=0;let lcdAddr=0,lcdEntryInc=true,lcdDD=new Uint8Array(0x80);lcdDD.fill(32);let audioCtx=null,audioUnlocked=false,pcmCache=new Map();let cpu=null,running=true,lastFrame=performance.now(),cycleDebt=0;const ledNames=['PATT/SONG','PLAY','RECORD','VOICE','TUNE','MIX','TEMPO','MIDI'];
function kbRead(){let d=0xff;for(let i=0;i<6;i++)if(((matrixSelect>>i)&1)===0)d&=columns[i];return d}
function lcdWrite(off,v){if(off===0){if(v&0x80)lcdAddr=v&0x7f;else if(v===0x01){lcdDD.fill(32);lcdAddr=0}else if(v===0x02){lcdAddr=0}else if((v&0xfc)===0x04)lcdEntryInc=!!(v&2)}else{lcdDD[lcdAddr]=v;lcdAddr=(lcdAddr+(lcdEntryInc?1:-1))&0x7f}renderLCD()}
function lcdRead(off){if(off===0)return lcdAddr&0x7f;const v=lcdDD[lcdAddr];lcdAddr=(lcdAddr+(lcdEntryInc?1:-1))&0x7f;return v}
function renderLCD(){for(const [id,base] of [['lcd0',0],['lcd1',0x40]]){let s='';for(let i=0;i<16;i++){const c=lcdDD[base+i];s+=c>=32&&c<127?String.fromCharCode(c):' '}$(id).textContent=s}}
function renderLEDs(){document.querySelectorAll('.led').forEach((e,i)=>{let on;if(i===0)on=!!(ledByte&1);else on=!((ledByte>>i)&1);e.classList.toggle('on',on)})}
function xread(a){if(a===0)return kbRead();if(a===6||a===7)return lcdRead(a-6);if(a>=0x8000)return nvram[a-0x8000];return 0xff}
function xwrite(a,v){if(a>=0x8000){nvram[a-0x8000]=v;return}if(a===2){dmWrite(v);return}if(a===4){ledByte=v;renderLEDs();return}if(a===6||a===7){lcdWrite(a-6,v);return}if(a===8){matrixSelect=v;return}}
function makeCPU(){cpu=new MCS51(FW,{portRead:(p,l)=>p===1?slider:(p===3?0xff:l),xread,xwrite});dmBytes=[];lastCmd=null;cmdCount=0;lcdAddr=0;lcdDD.fill(32);ledByte=0xff;renderLCD();renderLEDs();$('cpuStat').textContent='BOOTING 80C31';$('cpuStat').className='warn'}
function signed8(b){return b<128?b:b-256}
function decodeVoice(ptr){if(pcmCache.has(ptr))return pcmCache.get(ptr);let pos=ptr>>>0,shift=8,out=[],guard=0;while(pos<SOUND.length&&guard++<SOUND.length){let s=signed8(SOUND[pos++]);if(s===-128){let n=1;if(shift>0)shift--;while(pos<SOUND.length&&signed8(SOUND[pos])===-128){pos++;n++;if(n>=3){const f=Float32Array.from(out);pcmCache.set(ptr,f);return f}}continue}out.push(-(s*(1<<shift))/32768)}const f=Float32Array.from(out);pcmCache.set(ptr,f);return f}
function unlockAudio(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audioCtx||audioCtx.state==='closed')audioCtx=new AC();if(audioCtx.state!=='running')audioCtx.resume();const b=audioCtx.createBuffer(1,1,48000),s=audioCtx.createBufferSource();s.buffer=b;s.connect(audioCtx.destination);s.start(0);audioUnlocked=true;$('audStat').textContent='UNLOCKED / FIRMWARE DM3AG';$('audStat').className='good'}catch(e){$('audStat').textContent='WEB AUDIO BLOCKED';$('audStat').className='warn'}}
function playDM(ptr){if(!audioCtx||!audioUnlocked||ptr<=0)return;const pcm=decodeVoice(ptr);if(!pcm.length)return;const b=audioCtx.createBuffer(1,pcm.length,48000);b.copyToChannel(pcm,0);const s=audioCtx.createBufferSource(),g=audioCtx.createGain();s.buffer=b;g.gain.value=.78;s.connect(g);g.connect(audioCtx.destination);s.start()}
function dmWrite(v){dmBytes.push(v&255);if(dmBytes.length<5)return;const c=dmBytes.splice(0,5),ptr=(c[0]<<12)|(c[1]<<4)|(c[2]>>4);lastCmd={c,ptr,low:c[2]&15,vol:c[3],pan:(c[4]>>5)&7,out:(c[4]&0x10)?1:2};cmdCount++;if(ptr>0)playDM(ptr);updateDebug()}
function updateDebug(){if(!cpu)return;const pc=cpu.pc.toString(16).padStart(4,'0').toUpperCase();let d=`PC $${pc}   machine cycles ${cpu.cycles.toLocaleString()}   DM3AG packets ${cmdCount}`;if(lastCmd)d+=`\nDM3AG ${lastCmd.c.map(x=>x.toString(16).padStart(2,'0').toUpperCase()).join(' ')} → ROM $${lastCmd.ptr.toString(16).padStart(5,'0').toUpperCase()}  rawTune=${lastCmd.low} rawVol=$${lastCmd.vol.toString(16).padStart(2,'0')} panBits=${lastCmd.pan} out=${lastCmd.out}`;$('debug').textContent=d}
function runCycles(n){const end=cpu.cycles+n;let guard=0;try{while(cpu.cycles<end&&guard++<n*2+1000)cpu.step()}catch(e){running=false;$('cpuStat').textContent='CPU ERROR';$('cpuStat').className='warn';$('debug').textContent='CPU ERROR: '+e.message+'\n'+$('debug').textContent;console.error(e)}}
function frame(t){if(running){const dt=Math.min(0.05,(t-lastFrame)/1000);lastFrame=t;cycleDebt+=dt*1000000;const todo=Math.min(50000,cycleDebt|0);if(todo>0){runCycles(todo);cycleDebt-=todo}if(cpu.cycles>2500000){$('cpuStat').textContent='RUNNING REAL OS';$('cpuStat').className='good'}if((frame.count++&7)===0)updateDebug()}requestAnimationFrame(frame)}frame.count=0;
function pressMatrix(col,bit,el){unlockAudio();columns[col]&=~(1<<bit);el&&el.classList.add('down');setTimeout(()=>{columns[col]|=(1<<bit);el&&el.classList.remove('down')},85)}
function buildUI(){const lr=$('ledrow');ledNames.forEach(n=>{const e=document.createElement('span');e.className='led';e.textContent=n;lr.appendChild(e)});for(let c=0;c<4;c++)for(let b=0;b<8;b++){const e=document.createElement('button');e.className='ctrl';e.textContent=MATRIX[c][b];e.onclick=()=>pressMatrix(c,b,e);$('controls').appendChild(e)}for(let c=4;c<6;c++)for(let b=0;b<8;b++){const e=document.createElement('button');e.className='pad';e.textContent=MATRIX[c][b];e.onclick=()=>pressMatrix(c,b,e);$('pads').appendChild(e)}}
$('slider').oninput=e=>{slider=+e.target.value;$('sliderv').textContent=slider};$('resetBtn').onclick=()=>{unlockAudio();if(FW&&SOUND){makeCPU();lastFrame=performance.now();cycleDebt=0;running=true}};bootOnline();
