(()=>{const FIXED_STEPS=16;window.__pass28AudioKilled=false;
function force16(){try{patternLength=FIXED_STEPS}catch(_){}for(const id of ['patternLen','appPatternLen','p26PatternLen']){const el=document.getElementById(id);if(!el)continue;el.innerHTML=id==='p26PatternLen'?'<option value="16">16 steps</option>':'<option value="16">16</option>';el.value='16';el.disabled=true;el.setAttribute('aria-label','Pattern length: fixed 16 steps')}try{localStorage.setItem('dm3ag.patternLength','16')}catch(_){}}
function decorateSeq(){const s=document.getElementById('seq');if(!s)return;s.querySelectorAll('.hdr[data-s],.step[data-s]').forEach(el=>{const st=+el.dataset.s;if(!Number.isFinite(st))return;const group=Math.floor(st/4),sub=st%4;el.classList.toggle('downBeat',sub===0);el.classList.toggle('beatEnd',sub===3);el.classList.toggle('beatBandAlt',(group&1)===1);el.dataset.beat=String(group+1);el.dataset.sub=String(sub);if(el.classList.contains('hdr')){el.textContent=sub===0?String(group+1):(['','e','&','a'][sub]);el.title='Beat '+(group+1)+(sub===0?'':' '+['','e','&','a'][sub])}});const wrap=s.closest('.seqwrap');if(!wrap)return;let ruler=wrap.querySelector('.seqBeatRuler');if(!ruler){ruler=document.createElement('div');ruler.className='seqBeatRuler';wrap.insertBefore(ruler,s)}ruler.innerHTML='<span class="beatSpacer"></span>'+[1,2,3,4].map(n=>'<b class="beatGroup">BEAT '+n+'</b>').join('');requestAnimationFrame(()=>{const label=s.querySelector('.padHdr')?.getBoundingClientRect().width||104;const width=Math.max(s.scrollWidth,wrap.clientWidth);ruler.style.width=width+'px';ruler.style.gridTemplateColumns=label+'px repeat(4,minmax(0,1fr))'})}
try{const baseRender=renderSeq;renderSeq=function(){patternLength=FIXED_STEPS;const out=baseRender.apply(this,arguments);decorateSeq();return out}}catch(_){}
try{duplicateBar=function(){force16();renderSeq();try{lcd('16 STEP PATTERN','ONE BAR • 4 BEATS')}catch(_){}}}catch(_){}
try{const baseTrigger=triggerPad;triggerPad=function(){if(document.hidden||window.__pass28AudioKilled)return;return baseTrigger.apply(this,arguments)}}catch(_){}
function killAudio(closeContext){window.__pass28AudioKilled=true;try{playing=false}catch(_){}try{clearTimeout(seqTimer);seqTimer=null}catch(_){}try{stepIndex=0}catch(_){}try{document.querySelectorAll('.step,.seq .hdr[data-s]').forEach(e=>e.classList.remove('playhead'))}catch(_){}try{panicIOSSlots()}catch(_){}try{if(engine&&engine.panic)engine.panic()}catch(_){}try{if(ctx&&ctx.state!=='closed'){if(closeContext){const c=ctx;try{c.close()}catch(_){}ctx=null;engine=null;engineReady=false}else{try{ctx.suspend()}catch(_){}}}}catch(_){}}
window.__pass28StopAll=killAudio;
const isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
function lockGate(){if(!isiOS)return;document.body.classList.add('iosAudioLocked');const st=document.getElementById('iosAudioState');if(st)st.textContent='AUDIO LOCKED';const es=document.getElementById('engineStat');if(es){es.textContent='TAP TO START';es.className='warn'}}
function installGate(){if(!isiOS)return;const gate=document.getElementById('iosAudioGate');let old=gate?.querySelector('#iosAudioStart');if(!gate||!old)return;const btn=old.cloneNode(true);old.replaceWith(btn);const state=gate.querySelector('#iosAudioState');const unlock=ev=>{if(ev){try{ev.preventDefault()}catch(_){}try{ev.stopPropagation()}catch(_){}}if(state)state.textContent='STARTING AUDIO…';try{if(navigator.audioSession&&'type' in navigator.audioSession){try{navigator.audioSession.type='playback'}catch(_){}}const c=ensureIOSContextSync();try{const b=c.createBuffer(1,128,c.sampleRate||48000),src=c.createBufferSource(),g=c.createGain();src.buffer=b;g.gain.value=.00001;src.connect(g);g.connect(c.destination);src.start(0)}catch(_){}try{c.resume()}catch(_){}window.__pass28AudioKilled=false;document.body.classList.remove('iosAudioLocked');if(state)state.textContent='AUDIO READY';const es=document.getElementById('engineStat');if(es){es.textContent=c.state==='running'?'ACTIVE':'READY — TAP PAD';es.className='good'}try{lcd('AUDIO READY','TAP A PAD OR PRESS PLAY')}catch(_){}}catch(e){console.error(e);if(state)state.textContent='AUDIO START FAILED — TAP AGAIN'}};btn.addEventListener('touchstart',unlock,{passive:false});btn.addEventListener('pointerdown',unlock,{passive:false});btn.addEventListener('click',unlock,{passive:false});lockGate()}
document.addEventListener('visibilitychange',()=>{if(document.hidden)killAudio(false);else{killAudio(false);lockGate()}},true);window.addEventListener('pagehide',()=>killAudio(true),true);window.addEventListener('beforeunload',()=>killAudio(true),true);window.addEventListener('pageshow',()=>{killAudio(false);lockGate()},true);
const ready=()=>{force16();installGate();try{renderSeq()}catch(_){}const help=document.getElementById('p25Help');if(help)help.innerHTML=help.innerHTML.replace(/Set Length to 16, 32, 48 or 64\./g,'Patterns use one fixed 16-step bar (4 beats).');document.querySelectorAll('[data-menu-action="length"]').forEach(el=>el.style.display='none');setTimeout(()=>{force16();try{renderSeq()}catch(_){}},80)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();window.addEventListener('resize',()=>setTimeout(decorateSeq,50),{passive:true});window.addEventListener('orientationchange',()=>setTimeout(decorateSeq,150),{passive:true})})();