
(()=>{
 const SRC={
  onlyTab:'https://www.chords-and-tabs.net/song/name/nine-inch-nails-only-13',
  onlyCaptain:'https://www.patreon.com/posts/nine-inch-nails-69941804',
  onlyStructure:'https://songparts.com/songs/nine-inch-nails/only',
  closerTab:'https://muzikum.eu/en/nine-inch-nails/closer-drum-tab',
  closerCaptain:'https://www.patreon.com/captainpikant/sitemap',
  closerStructure:'https://songparts.com/songs/nine-inch-nails/closer',
  wishTab:'https://www.chords-and-tabs.net/song/name/nine-inch-nails-wish-12',
  ratings:'https://www.ttabs.com/tabs/n/nine_inch_nails/Drum_tabs',
  songsterr:'https://www.songsterr.com/a/wsa/nine-inch-nails-tabs-a4369?inst=drum'
 };
 const E=(o)=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,String(v)]));
 function add(p){if(!HISTORY_PATTERNS.some(x=>x.id===p.id))HISTORY_PATTERNS.push(p)}
 function exp(roles){return Object.fromEntries(Object.entries(roles).map(([k,v])=>[k,v.join(',')]))}
 function mk(id,title,section,bpm,length,roles,extra={}){return {id,artist:'Nine Inch Nails',title,section,genre:'industrial',bpm,length,machine:'NIN DRUM TRANSCRIPTION • ADAPTED TO CURRENT MODEL',confidence:extra.confidence||'PUBLIC DRUM TAB TRANSCRIPTION',sourceLabel:extra.sourceLabel||'Public drum-tab section adapted to the 16/32-step sequencer.',sources:extra.sources||[],roles,expected:exp(roles),songGroup:extra.songGroup||('nin-'+title.toLowerCase().replace(/[^a-z0-9]+/g,'-')),sectionOrder:extra.sectionOrder||1,sectionType:extra.sectionType||section,captain:!!extra.captain,tabRating:extra.tabRating||'',quantized:!!extra.quantized};}
 const only=HISTORY_PATTERNS.find(p=>p.id==='nin-only-main');if(only){Object.assign(only,{songGroup:'nin-only',section:'Verse / Main Groove',sectionOrder:1,sectionType:'Verse',sources:[SRC.onlyTab,SRC.onlyCaptain,SRC.onlyStructure],sourceLabel:'Public drum tab + Captain Pikant NIN transcription cross-check.',captain:true});}
 add(mk('nin-only-openhats','Only','Open-Hat Passage',112,16,{kick:[0,8],snare:[4,12],openhat:[2,6,10,14]},{songGroup:'nin-only',sectionOrder:2,sectionType:'Open-hat passage',captain:true,sources:[SRC.onlyTab,SRC.onlyCaptain,SRC.onlyStructure],sourceLabel:'The public drum tab calls for all-open hats in the “there is no you” passage.'}));
 add(mk('nin-only-tamb','Only','Third Verse — Tambourine Layer',112,16,{kick:[0,8],snare:[4,12],closedhat:[2,6,10],openhat:[14],tambourine:[0,2,4,6,8,10,12,14]},{songGroup:'nin-only',sectionOrder:3,sectionType:'Third Verse',captain:true,sources:[SRC.onlyTab,SRC.onlyCaptain,SRC.onlyStructure],sourceLabel:'Public tab notes an eighth-note tambourine layer in the third verse.'}));
 const closer=HISTORY_PATTERNS.find(p=>p.id==='nin-closer-main');if(closer){Object.assign(closer,{songGroup:'nin-closer',section:'Part 3 — Full Hats + Open Hats',sectionOrder:3,sectionType:'Part 3',sources:[SRC.closerTab,SRC.closerCaptain,SRC.closerStructure],sourceLabel:'Muzikum public drum tab Part 3; Captain Pikant catalogues Closer as a dedicated NIN pattern.',captain:true});}
 add(mk('nin-closer-p1','Closer','Part 1 — Sparse Kick / Snare',90,16,{kick:[0,4,8,12],snare:[4,12]},{songGroup:'nin-closer',sectionOrder:1,sectionType:'Part 1',captain:true,sources:[SRC.closerTab,SRC.closerCaptain,SRC.closerStructure],sourceLabel:'Exact public drum-tab Part 1 event layout.'}));
 add(mk('nin-closer-p2','Closer','Part 2 — Closed-Hat Drive',90,16,{kick:[0,4,8,12],snare:[4,12],closedhat:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]},{songGroup:'nin-closer',sectionOrder:2,sectionType:'Part 2',captain:true,sources:[SRC.closerTab,SRC.closerCaptain,SRC.closerStructure],sourceLabel:'Exact public drum-tab Part 2 event layout.'}));
 add(mk('nin-closer-p4','Closer','Part 4 — Open-Hat Drive',90,16,{kick:[0,4,8,12],snare:[4,12],openhat:[2,6,10,14]},{songGroup:'nin-closer',sectionOrder:4,sectionType:'Part 4',captain:true,sources:[SRC.closerTab,SRC.closerCaptain,SRC.closerStructure],sourceLabel:'Exact public drum-tab Part 4 event layout.'}));
 add(mk('nin-closer-p5','Closer','Part 5 — 2-Bar Syncopated Break',90,32,{kick:[0,1,4,8,9,12,16,17,19,20,22,24,28,30],snare:[4,12,20,28],clap:[4,12,20,28],openhat:[2,6,10,14,18,22,26,30]},{songGroup:'nin-closer',sectionOrder:5,sectionType:'Part 5',captain:true,sources:[SRC.closerTab,SRC.closerCaptain,SRC.closerStructure],sourceLabel:'Two-bar Part 5 from the public tab; layered clap represents the tab note that two snares appear together.'}));
 add(mk('nin-closer-p6','Closer','Part 6 — Late Groove',90,16,{kick:[0,1,3,4,6,8,9,11,12],snare:[4,12],closedhat:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],openhat:[2,6,10,14]},{songGroup:'nin-closer',sectionOrder:6,sectionType:'Part 6',captain:true,sources:[SRC.closerTab,SRC.closerCaptain,SRC.closerStructure],sourceLabel:'Public drum-tab Part 6 adapted directly to a 16-step bar.'}));
 // Wish has one of the better-rated public NIN drum tabs. Speed-note rolls are quantized to the app's 16-step grid rather than pretending sub-step precision.
 add(mk('nin-wish-verse','Wish','Verse — Tom Roll Pulse',135,16,{kick:[0,4,8,12],tom1:[1,2,3,5,6,7,9,10,11,13,14,15]},{songGroup:'nin-wish',sectionOrder:1,sectionType:'Verse',tabRating:'4.14/5 · 7 ratings',quantized:true,sources:[SRC.wishTab,SRC.ratings],sourceLabel:'Highly rated public drum tab; speed-note tom rolls quantized to 16 steps.',confidence:'PUBLIC DRUM TAB • ROLLS QUANTIZED'}));
 add(mk('nin-wish-chorus','Wish','Chorus — Roll + Backbeat',135,16,{kick:[0,4,8,12],snare:[4,12],tom1:[1,2,3,5,6,7,9,10,11,13,14,15]},{songGroup:'nin-wish',sectionOrder:2,sectionType:'Chorus',tabRating:'4.14/5 · 7 ratings',quantized:true,sources:[SRC.wishTab,SRC.ratings],sourceLabel:'Verse roll pattern plus chorus snare from the public drum tab; rolls quantized.',confidence:'PUBLIC DRUM TAB • ROLLS QUANTIZED'}));
 add(mk('nin-wish-post','Wish','Post-Chorus Fill',135,16,{kick:[0,4,8,12],snare:[1,2,3,5,6,7,9,10,11,13,14,15]},{songGroup:'nin-wish',sectionOrder:3,sectionType:'Post-Chorus Fill',tabRating:'4.14/5 · 7 ratings',quantized:true,sources:[SRC.wishTab,SRC.ratings],sourceLabel:'Public post-chorus snare-speed-note fill, quantized to the app grid.',confidence:'PUBLIC DRUM TAB • FILL QUANTIZED'}));
 const oldRole=historyRolePad;historyRolePad=function(role){if(role==='tambourine'){const n=padState.map(p=>String(p.label||'').toUpperCase());let i=n.findIndex(x=>x.includes('TAMBOURINE'));if(i<0)i=n.findIndex(x=>x.includes('SHAKER')||x.includes('PERC'));return i}return oldRole(role)};
 const CANDIDATES=[
  ['Hyperpower!','5/5 · 10 ratings','Songsterr drum track + tTabs rating'],
  ['The Beginning of the End','5/5 · 4 ratings','Songsterr drum track + Ultimate Guitar/Pro indexed by 911Tabs'],
  ['Letting You','5/5 · 3 ratings','Songsterr drum track + tTabs rating'],
  ['Just Like You Imagined','5/5 · 3 ratings','tTabs drum tab'],
  ['Discipline','4/5 · 4 ratings','Songsterr drum track + tTabs rating'],
  ["We're In This Together",'4/5 · 4 ratings','tTabs drum tab']
 ];
 window.P39SectionChoice=window.P39SectionChoice||{};
 function groupKey(p){return p.songGroup||((p.artist||'')+'||'+(p.title||''));}
 function preview(p){const n=Math.min(32,Math.max(16,+p.length||16)),roles=Object.keys(p.roles||{});let h='<div class="patternGridPreview p39Preview" style="grid-template-columns:64px repeat('+n+',minmax(7px,1fr))"><span></span>'+Array.from({length:n},(_,i)=>'<b>'+(i%16+1)+'</b>').join('');for(const role of roles){h+='<span class="lab">'+role.toUpperCase()+'</span>';const set=new Set(p.roles[role]||[]);for(let i=0;i<n;i++)h+='<i class="'+(set.has(i)?'on':'')+'"></i>'}return h+'</div>'}
 function filtered(p){return historyPatternFilter==='all'||p.genre===historyPatternFilter||(historyPatternFilter==='alesis'&&p.alesis)}
 function sources(p){return (p.sources||[]).map((u,i)=>'<a href="'+u+'" target="_blank" rel="noopener">SOURCE '+(i+1)+'</a>').join(' • ')}
 function updateCard(card,p,variants){card.dataset.selected=p.id;const sec=card.querySelector('.p39SectionInfo');if(sec)sec.textContent=p.section;const meta=card.querySelector('.patternMeta');if(meta)meta.innerHTML='<span class="patternBadge verified">'+(historyPatternValid(p)?'GRID VERIFIED':'BLOCKED')+'</span><span class="patternBadge '+p.genre+'">'+String(p.genre).toUpperCase()+'</span>'+(p.captain?'<span class="patternBadge p38Captain">CAPTAIN PIKANT REF</span>':'')+(variants.length>1?'<span class="patternBadge sections">'+variants.length+' SECTIONS</span>':'')+(p.tabRating?'<span class="patternBadge rating">TAB '+p.tabRating+'</span>':'')+(p.quantized?'<span class="patternBadge quantized">QUANTIZED ROLLS</span>':'')+'<span class="patternBadge">'+p.bpm+' BPM</span><span class="patternBadge">'+p.length+' STEPS</span>';const m=card.querySelector('.p39Machine');if(m)m.innerHTML='<b>'+p.machine+'</b><br>'+p.confidence;const pv=card.querySelector('.p39PreviewHost');if(pv)pv.innerHTML=preview(p);const src=card.querySelector('.patternSource');if(src)src.innerHTML=p.sourceLabel+'<br>'+sources(p);const l=card.querySelector('[data-p39-load]'),pl=card.querySelector('[data-p39-play]');if(l){l.dataset.p39Load=p.id;l.disabled=!historyPatternValid(p)}if(pl){pl.dataset.p39Play=p.id;pl.disabled=!historyPatternValid(p)}}
 renderHistoryPatterns=function(){const g=document.getElementById('historyPatternGrid');if(!g)return;g.innerHTML='';const groups=new Map();for(const p of HISTORY_PATTERNS){if(!filtered(p))continue;const k=groupKey(p);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(p)}for(const [k,vars0] of groups){const variants=vars0.slice().sort((a,b)=>(a.sectionOrder||0)-(b.sectionOrder||0));let chosen=variants.find(p=>p.id===P39SectionChoice[k])||variants[0];P39SectionChoice[k]=chosen.id;const d=document.createElement('article');d.className='patternCard';d.dataset.multisection=variants.length>1?'1':'0';d.innerHTML='<div class="patternArtist">'+chosen.artist+'</div><h3>'+chosen.title+'</h3>'+(variants.length>1?'<div class="patternSectionRow"><label>SECTION</label><select class="patternSectionSelect">'+variants.map(p=>'<option value="'+p.id+'"'+(p.id===chosen.id?' selected':'')+'>'+p.section+'</option>').join('')+'</select></div>':'')+'<div class="patternSectionInfo p39SectionInfo">'+chosen.section+'</div><div class="patternMeta"></div><div class="mini p39Machine"></div><div class="p39PreviewHost"></div><div class="patternActions"><button data-p39-load="'+chosen.id+'">LOAD SECTION</button><button data-p39-play="'+chosen.id+'">LOAD + PLAY</button></div><div class="patternSource"></div>';g.appendChild(d);updateCard(d,chosen,variants);const sel=d.querySelector('.patternSectionSelect');if(sel)sel.onchange=()=>{const p=variants.find(x=>x.id===sel.value)||variants[0];P39SectionChoice[k]=p.id;updateCard(d,p,variants)};d.querySelector('[data-p39-load]').onclick=e=>{const id=e.currentTarget.dataset.p39Load;P39SectionChoice[k]=id;loadHistoryPattern(id,false)};d.querySelector('[data-p39-play]').onclick=e=>{const id=e.currentTarget.dataset.p39Play;P39SectionChoice[k]=id;loadHistoryPattern(id,true)}}const q=document.getElementById('historyResearchQueue');if(q){q.innerHTML='<details class="p39Candidates" open><summary>HIGH-RATED NIN DRUM-TAB CANDIDATES</summary>'+CANDIDATES.map(x=>'<div class="p39Candidate"><span><b>'+x[0]+'</b><br>'+x[2]+'</span><span class="p39Rating">'+x[1]+'</span></div>').join('')+'</details>'+HISTORY_RESEARCH_QUEUE.map(x=>'<div class="queueItem"><span><b>'+x[0]+' — '+x[1]+'</b><br>'+x[2]+'</span><span class="queueState">RESEARCH</span></div>').join('')}};
 const baseLoad=loadHistoryPattern;loadHistoryPattern=function(id,playNow=false){const was=document.body.dataset.view==='patterns',content=document.querySelector('.appContent'),main=document.querySelector('.appMain'),ct=content?.scrollTop||0,mt=main?.scrollTop||0,wy=scrollY||0;const ok=baseLoad(id,playNow);if(ok!==false&&was){document.body.dataset.view='patterns';document.querySelectorAll('.viewBtn').forEach(b=>b.classList.toggle('active',b.dataset.view==='patterns'));renderHistoryPatterns();requestAnimationFrame(()=>{if(content)content.scrollTop=ct;if(main)main.scrollTop=mt;scrollTo(0,wy);const p=HISTORY_PATTERNS.find(x=>x.id===id),k=p&&groupKey(p);if(k){const card=[...document.querySelectorAll('.patternCard')].find(c=>c.dataset.selected===id||c.querySelector('[data-p39-load="'+id+'"]'));card?.scrollIntoView({block:'nearest'})}})}return ok};
 function init(){const h=document.querySelector('#patternsView .p26HeadActions span');if(h)h.textContent='SONG + SECTION LIBRARY';renderHistoryPatterns()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
